### ISSUE TITLE
IpRateLimitMiddleware can't parse caller IP

### ISSUE THREAD

**Issue by kspearrin** [stefanprodan/AspNetCoreRateLimit#10]
Getting this somewhat frequently in production on an Azure Web App. Not able to reproduce since my home IP parses correctly. Any ideas?

```
Exception: IpRateLimitMiddleware can't parse caller IP
Type: System.Exception

Stack Trace

System.Exception: IpRateLimitMiddleware can't parse caller IP ---> System.FormatException: An invalid IP address was specified. ---> System.Net.Sockets.SocketException: An invalid argument was supplied
   --- End of inner exception stack trace ---
   at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
   at AspNetCoreRateLimit.ReversProxyIpParser.GetClientIp(HttpContext context)
   at AspNetCoreRateLimit.IpRateLimitMiddleware.SetIdentity(HttpContext httpContext)
   --- End of inner exception stack trace ---
   at AspNetCoreRateLimit.IpRateLimitMiddleware.SetIdentity(HttpContext httpContext)
   at AspNetCoreRateLimit.IpRateLimitMiddleware.d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.d__2.MoveNext()
```

**Comment by stefanprodan** [comment]
Can you view the IPs that are causing this? Maybe in the trace logs?

**Comment by kspearrin** [comment]
I was not able to get the IPs at the time. This happened after I did the first deployment of the application since implementing the rate limiter. It happened intermittently for several minutes after the deployment, however, 4 days later (now) it has not happened since. Weird...

**Comment by stefanprodan** [comment]
One thing you could do is implement your own [ReversProxyIpParser](https://github.com/stefanprodan/AspNetCoreRateLimit/blob/master/src/AspNetCoreRateLimit/Net/ReversProxyIpParser.cs) and do a try/catch/throw inside GetClientIp and append to the exception message all the IPs from the Request.Headers.

**Comment by kspearrin** [comment]
I forgot that the reason it stopped happening was that I pushed another hotfix to catch that exception.

I did as you suggested to log the `X-Forwarded-For` header. The IPs appear to be very standard IPs with a port on the end of them for some reason. ex: `xx.xxx.xxx.159:28893`, `xx.xx.xxx.15:6555`, and `xx.xx.xxx.15:6558` (same IP as the previous but with different port this time).

NOTE: I replaced some of the numbers with `x` for privacy reasons.

One of the IPs logged this time is mine.

**Comment by stefanprodan** [comment]
I've published v1.0.5 on NuGet with a fix for this issue. Please let me know if it works for you.

Thanks

**Comment by carlos-anaya** [comment]
Hi, I ran into a similar issue, on appsettings.json I have:
`"RealIpHeader": "X-Forwarded-For"`
And the request header is:
`X-Forwarded-For: 205.156.136.211, 192.168.29.47:54610`
And I get the same exception: _IpRateLimitMiddleware can't parse caller IP_
I'm currently using v1.0.5
Thanks

**Comment by stefanprodan** [comment]
@carlos-anaya your use case is different. Please get v2.1.0 from NuGet and tell me if it's ok now.

Thanks

**Comment by carlos-anaya** [comment]
Yup, it works. Many thanks for your quick answer @stefanprodan!
