### ISSUE TITLE
Got a fatal error!!!

### ISSUE THREAD

**Issue by lampo1024** [stefanprodan/AspNetCoreRateLimit#122]
I got a fatal error in my production environment, as follows:

```csharp
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AspNetCoreRateLimit.Bits.GetBitMask(Int32 sizeOfBuff, Int32 bitLen)
   at AspNetCoreRateLimit.IpAddressRange..ctor(String ipRangeString)
   at AspNetCoreRateLimit.IpAddressUtil.ContainsIp(List`1 ipRules, String clientIp)
   at AspNetCoreRateLimit.IpRateLimitProcessor.IsWhitelisted(ClientRequestIdentity requestIdentity)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at ZNetCS.AspNetCore.IPFiltering.IPFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Here is my config:

```json
"IpRateLimiting": {
        "EnableEndpointRateLimiting": true,
        "StackBlockedRequests": false,
        "RealIpHeader": "X-Real-IP",
        "ClientIdHeader": "X-ClientId",
        "HttpStatusCode": 429,
        "IpWhitelist": [],
        "EndpointWhitelist": [ "get:/api/license", "*:/api/status", "*:/img/*", "*:fonts/fontawesome-webfont.woff" ],
        "ClientWhitelist": [ "dev-id-1", "dev-id-2" ],
        "GeneralRules": [
            {
                "Endpoint": "*",
                "Period": "1s",
                "Limit": 3
            },
            {
                "Endpoint": "*",
                "Period": "15m",
                "Limit": 50
            },
            {
                "Endpoint": "*",
                "Period": "12h",
                "Limit": 500
            },
            {
                "Endpoint": "*",
                "Period": "1d",
                "Limit": 1000
            }
        ]
    }
```

I use this library for a few days, everything is working fine, but dozens of minutes ago, this error occurred for all request. My website can't access any more.

I comment this line:

// app.UseIpRateLimiting();

And it's back to normal.

**Comment by cristipufu** [comment]
Hi @lampo102, thanks for reporting this issue. I will take a look soon. Can you somehow find out the the client IPs that are trying to connect to your website and breaking the rate limiter? These seem like IP parsing failures

**Comment by lampo1024** [comment]
During that time, all client IPs were blocked.

![1](https://user-images.githubusercontent.com/3262079/79930403-03ee1580-847b-11ea-9530-839dac12d460.png)

**Comment by EminemJK** [comment]
I comment this line:

// app.UseIpRateLimiting();

And it's back to normal.

I am the same, to remove the normal

**Comment by cristipufu** [comment]
@lampo1024 this could only happen if you have an invalid `IpWhitelist` address in your options config:
```json
"IpRateLimiting": {
    "IpWhitelist": [ "::1/10", "192.168.0.0/24" ],
}
```
The `IpAddressRange` ctor is only used to parse the IP ranges from the configuration options.

I can see that in the configuration you've posted, the `IpWhitelist` is an empty list, so I'm sorry but I really don't understand how this could happen, unless that gets overriden somehow by other config files or something in your app/deployment.
