### ISSUE TITLE
When MemoryCache has a size limit then AspNetCoreRateLimit throws InvalidOperationException exceptions

### ISSUE THREAD

**Issue by credfeto** [stefanprodan/AspNetCoreRateLimit#166]
Cache entry must specify a value for Size when SizeLimit is set.
```
Stacktrace:
   at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value, MemoryCacheEntryOptions options)
   at AspNetCoreRateLimit.MemoryCacheRateLimitStore\u00601.SetAsync(String id, T entry, Nullable\u00601 expirationTime, CancellationToken cancellationToken)
   at AspNetCoreRateLimit.RateLimitProcessor.ProcessRequestAsync(ClientRequestIdentity requestIdentity, RateLimitRule rule, CancellationToken cancellationToken)
   at AspNetCoreRateLimit.RateLimitMiddleware\u00601.Invoke(HttpContext context)
   at FunFair.FunWallet.Api.Middleware.AppPrivateIpMiddleware.InvokeAsync(HttpContext context)
   at FunFair.FunWallet.Api.Middleware.AppNotFoundExceptionHandlingMiddleware.InvokeAsync(HttpContext context)
   at FunFair.FunWallet.Common.Api.Middleware.JwtUserNullExceptionHandlingMiddleware.InvokeAsync(HttpContext context)
   at FunFair.Common.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context)```

Other parts of our system expect that size limit is enforced

**Comment by thomasgalliker** [comment]
Did you check issue #148? Seems like this is the same problem.
