### ISSUE TITLE
Getting WRONGTYPE Operation against a key holding the wrong kind of value after upgrading 3.2.2 -> 4.x.x using AspNetCoreRateLimit.Redis

### ISSUE THREAD

**Issue by hulvei3** [stefanprodan/AspNetCoreRateLimit#338]
We are in the process of upgrading an existing service which includes AspBetCoreRateLimit to NET 6 from NET 5. When deploying we get a lot of the Redis exceptions: `WRONGTYPE Operation against a key holding the wrong kind of value` which propose some breaking change in the value types when we try to read from keys that have been set by an earlier version.

We didn't do many changes to the pipeline in between those versions, so we are a bit in the dark where to got from here. Tried to wipe the keys after deployment, but still not positive result.

Stack-trace: 
```
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_4dd896389061edf088699e7230bfd52bbea35edd): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value 
   at AspNetCoreRateLimit.Redis.RedisProcessingStrategy.IncrementAsync(String counterId, TimeSpan interval, Func`1 RateIncrementer) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit.Redis\RedisProcessingStrategy.cs:line 44
   at AspNetCoreRateLimit.Redis.RedisProcessingStrategy.ProcessRequestAsync(ClientRequestIdentity requestIdentity, RateLimitRule rule, ICounterKeyBuilder counterKeyBuilder, RateLimitOptions rateLimitOptions, CancellationToken cancellationToken) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit.Redis\RedisProcessingStrategy.cs:line 29
   at AspNetCoreRateLimit.ClientRateLimitProcessor.ProcessRequestAsync(ClientRequestIdentity requestIdentity, RateLimitRule rule, CancellationToken cancellationToken) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Core\ClientRateLimitProcessor.cs:line 36
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context) in C:\Users\User\Documents\Github\AspNetCoreRateLimit\src\AspNetCoreRateLimit\Middleware\RateLimitMiddleware.cs:line 57
   at ....Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at ....ApiStartup.<Configure>b__12_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by hulvei3** [comment]
Found out the issues. Since the introduction of the dedicated Redis package implementation where the interaction with the ratelimitstore is moved from a generic `IDistributedCache` to an actual redis implementation using `INCRBYFLOAT`, the logic is changed from replacing the full value (saving the count as a string I think) to increment the count value using a Redis lua script call. This is breaking during rollout when you have existing keys stored with the old version.
We were on to that and removed the existing keys on production after production, but the issue still persisted. We didn't realize that we had other applications sharing the same Client-Id policy and thereby still replacing the full value with a string count.

My mistake, also given that this is major version bump.
Adding a temporary key prefix fixed the issue for us during the rollout of all services sharing the same policies.
